/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Creates a new user account with unverified status and triggers an email verification flow.
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in user
         * @description Authenticates a user using email and password. On success, returns a short-lived access token in the JSON body, and sets the long-lived refresh token and CSRF companion token as HttpOnly and Lax cookies.
         */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description Rotates the active HttpOnly refresh token cookie and issues a new access token. Requires valid CSRF verification cookies and headers.
         */
        post: operations["refreshAccessToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out user
         * @description Revokes the user session and clears all authentication/CSRF cookies. Requires valid CSRF verification cookies and headers. Idempotent.
         */
        post: operations["logoutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify email address
         * @description Marks a user account email as verified using the opaque verification token received via email.
         */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend verification email
         * @description Resends an email verification link if the account exists and is not yet verified.
         */
        post: operations["resendVerificationEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request password reset link
         * @description Sends a password reset token via email if the account exists.
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset password
         * @description Resets the account password using the opaque token received in the password reset email.
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user profile
         * @description Retrieves profile details of the currently authenticated user. Requires a valid Bearer JWT.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /**
             * @example false
             * @enum {boolean}
             */
            success: false;
            error: {
                /**
                 * @description Machine-readable error code.
                 * @example UNAUTHORIZED
                 */
                code: string;
                /**
                 * @description Human-readable error description.
                 * @example Unauthorized
                 */
                message: string;
                /**
                 * Format: uuid
                 * @description Correlation ID for log tracing.
                 */
                requestId?: string;
            };
        };
        /**
         * @example {
         *       "success": true
         *     }
         */
        SuccessResponse: {
            /**
             * @example true
             * @enum {boolean}
             */
            success: true;
        };
        /**
         * @description Lifecycle state of a user account.
         * @example ACTIVE
         * @enum {string}
         */
        UserStatus: "ACTIVE" | "SUSPENDED" | "DELETED";
        UserResponse: {
            /**
             * Format: uuid
             * @description Unique user identifier (UUIDv7).
             * @example 0f3d2c4b-2d78-4b89-b20b-4dbe7c8472d8
             */
            id: string;
            /**
             * Format: email
             * @description User's registered email address.
             * @example john@example.com
             */
            email: string;
            /**
             * @description User's given name.
             * @example John
             */
            firstName: string;
            /**
             * @description User's family name.
             * @example Doe
             */
            lastName: string;
            /**
             * @description URL of the user's profile picture, or null if not set.
             * @example https://cdn.example.com/avatars/user.jpg
             */
            avatarUrl: string | null;
            /**
             * @description Whether the user has confirmed their email address.
             * @example true
             */
            emailVerified: boolean;
            status: components["schemas"]["UserStatus"];
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of when the account was created.
             * @example 2024-01-15T10:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of the last account update.
             * @example 2024-06-25T14:00:00.000Z
             */
            updatedAt: string;
        };
        /**
         * @example {
         *       "email": "john@example.com",
         *       "password": "Password123!",
         *       "firstName": "John",
         *       "lastName": "Doe"
         *     }
         */
        RegisterRequest: {
            /**
             * Format: email
             * @description Email address to register. Stored in lowercase.
             * @example john@example.com
             */
            email: string;
            /**
             * @description Must contain at least one uppercase letter and one digit. Max 72 chars (bcrypt limit).
             * @example Password123!
             */
            password: string;
            /**
             * @description User's given name.
             * @example John
             */
            firstName: string;
            /**
             * @description User's family name.
             * @example Doe
             */
            lastName: string;
        };
        /**
         * @example {
         *       "email": "john@example.com",
         *       "password": "Password123!"
         *     }
         */
        LoginRequest: {
            /**
             * Format: email
             * @description Registered email address.
             * @example john@example.com
             */
            email: string;
            /**
             * @description Account password.
             * @example Password123!
             */
            password: string;
        };
        /**
         * @example {
         *       "email": "john@example.com"
         *     }
         */
        ForgotPasswordRequest: {
            /**
             * Format: email
             * @description Email of the account to send the password-reset link to.
             * @example john@example.com
             */
            email: string;
        };
        /**
         * @example {
         *       "token": "reset-token",
         *       "newPassword": "NewPassword123!"
         *     }
         */
        ResetPasswordRequest: {
            /**
             * @description Opaque reset token received via email link.
             * @example reset-token
             */
            token: string;
            /**
             * @description Must contain at least one uppercase letter and one digit. Max 72 chars (bcrypt limit).
             * @example NewPassword123!
             */
            newPassword: string;
        };
        /**
         * @example {
         *       "token": "verification-token"
         *     }
         */
        VerifyEmailRequest: {
            /**
             * @description Opaque verification token received via email link.
             * @example verification-token
             */
            token: string;
        };
        /**
         * @example {
         *       "success": true,
         *       "data": {
         *         "user": {
         *           "id": "0f3d2c4b-2d78-4b89-b20b-4dbe7c8472d8",
         *           "email": "john@example.com",
         *           "status": "ACTIVE"
         *         }
         *       }
         *     }
         */
        RegisterResponse: {
            /**
             * @example true
             * @enum {boolean}
             */
            success: true;
            data: {
                user: {
                    /**
                     * Format: uuid
                     * @description Unique user identifier (UUIDv7).
                     * @example 0f3d2c4b-2d78-4b89-b20b-4dbe7c8472d8
                     */
                    id: string;
                    /**
                     * Format: email
                     * @description User's registered email address.
                     * @example john@example.com
                     */
                    email: string;
                    status: components["schemas"]["UserStatus"];
                };
            };
        };
        /**
         * @example {
         *       "success": true,
         *       "data": {
         *         "user": {
         *           "id": "0f3d2c4b-2d78-4b89-b20b-4dbe7c8472d8",
         *           "email": "john@example.com",
         *           "status": "ACTIVE"
         *         },
         *         "accessToken": "<jwt>"
         *       }
         *     }
         */
        LoginResponse: {
            /**
             * @example true
             * @enum {boolean}
             */
            success: true;
            /** @description The refresh token is rotated into the __Host-refresh HttpOnly cookie, not present in the body. */
            data: {
                user: {
                    /**
                     * Format: uuid
                     * @description Unique user identifier (UUIDv7).
                     * @example 0f3d2c4b-2d78-4b89-b20b-4dbe7c8472d8
                     */
                    id: string;
                    /**
                     * Format: email
                     * @description User's registered email address.
                     * @example john@example.com
                     */
                    email: string;
                    status: components["schemas"]["UserStatus"];
                };
                /**
                 * @description JWT access token signed with RS256. Valid for 15 minutes.
                 * @example <jwt>
                 */
                accessToken: string;
            };
        };
        /**
         * @example {
         *       "success": true,
         *       "data": {
         *         "user": {
         *           "id": "0f3d2c4b-2d78-4b89-b20b-4dbe7c8472d8",
         *           "email": "john@example.com",
         *           "status": "ACTIVE"
         *         },
         *         "accessToken": "<jwt>"
         *       }
         *     }
         */
        RefreshResponse: {
            /**
             * @example true
             * @enum {boolean}
             */
            success: true;
            /** @description The new refresh token is rotated into the __Host-refresh HttpOnly cookie. */
            data: {
                user: {
                    /**
                     * Format: uuid
                     * @description Unique user identifier (UUIDv7).
                     * @example 0f3d2c4b-2d78-4b89-b20b-4dbe7c8472d8
                     */
                    id: string;
                    /**
                     * Format: email
                     * @description User's registered email address.
                     * @example john@example.com
                     */
                    email: string;
                    status: components["schemas"]["UserStatus"];
                };
                /**
                 * @description Newly issued JWT access token signed with RS256. Valid for 15 minutes.
                 * @example <jwt>
                 */
                accessToken: string;
            };
        };
        /**
         * @example {
         *       "email": "john@example.com"
         *     }
         */
        ResendVerificationRequest: {
            /**
             * Format: email
             * @description Registered email address to resend verification link.
             * @example john@example.com
             */
            email: string;
        };
        /**
         * @example {
         *       "success": true,
         *       "data": {
         *         "id": "0f3d2c4b-2d78-4b89-b20b-4dbe7c8472d8",
         *         "email": "john@example.com",
         *         "firstName": "John",
         *         "lastName": "Doe",
         *         "avatarUrl": null,
         *         "emailVerified": true,
         *         "status": "ACTIVE",
         *         "createdAt": "2024-01-15T10:30:00.000Z",
         *         "updatedAt": "2024-06-25T14:00:00.000Z"
         *       }
         *     }
         */
        MeResponse: {
            /**
             * @example true
             * @enum {boolean}
             */
            success: true;
            data: components["schemas"]["UserResponse"];
        };
    };
    responses: {
        /** @description Request body or parameters failed schema validation. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "BAD_REQUEST",
                 *         "message": "Invalid email address",
                 *         "requestId": "018e1c2d-3f4a-7b8c-9d0e-1f2a3b4c5d6e"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication credentials are missing or invalid. */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "UNAUTHORIZED",
                 *         "message": "Unauthorized",
                 *         "requestId": "018e1c2d-3f4a-7b8c-9d0e-1f2a3b4c5d6e"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The authenticated user lacks the required permissions. */
        ForbiddenError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "FORBIDDEN",
                 *         "message": "Forbidden",
                 *         "requestId": "018e1c2d-3f4a-7b8c-9d0e-1f2a3b4c5d6e"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The requested resource does not exist. */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "NOT_FOUND",
                 *         "message": "Not Found",
                 *         "requestId": "018e1c2d-3f4a-7b8c-9d0e-1f2a3b4c5d6e"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description A resource with the same unique identifier already exists. */
        ConflictError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "CONFLICT",
                 *         "message": "Email already registered",
                 *         "requestId": "018e1c2d-3f4a-7b8c-9d0e-1f2a3b4c5d6e"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description An unexpected internal server error occurred. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "INTERNAL_SERVER_ERROR",
                 *         "message": "Internal Server Error",
                 *         "requestId": "018e1c2d-3f4a-7b8c-9d0e-1f2a3b4c5d6e"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description CSRF token obtained from the csrfToken cookie. Required only on endpoints relying on cookie auth (POST /auth/refresh and POST /auth/logout) to prevent CSRF attacks. The value must exactly match the value of the csrfToken cookie. */
        XCsrfToken: string;
        /** @description CSRF token stored in a Lax cookie (readable by frontend JavaScript, HttpOnly=false). Must match the x-csrf-token header. Rotated on refresh. */
        CsrfTokenCookie: string;
        /** @description HttpOnly Secure (in production) SameSite=Lax cookie containing the opaque refresh token. Rotated on refresh. Path=/. */
        RefreshTokenCookie: string;
    };
    requestBodies: never;
    headers: {
        /** @description Sets the __Host-refresh HttpOnly Secure (in production) SameSite=Lax cookie containing the opaque refresh token (7-day TTL). Rotated on refresh. Path=/. */
        SetRefreshTokenCookie: string;
        /** @description Sets the csrfToken SameSite=Lax cookie (readable by JS, HttpOnly=false) that must be echoed back in the x-csrf-token header. Rotated on refresh. Path=/. */
        SetCsrfCookie: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description User registration credentials and profile details. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User account registered successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["ConflictError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Login email and password. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful. Cookies set. */
            200: {
                headers: {
                    /** @description Sets the __Host-refresh (HttpOnly) and csrfToken cookies. See components headers. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    refreshAccessToken: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF token obtained from the csrfToken cookie. Required only on endpoints relying on cookie auth (POST /auth/refresh and POST /auth/logout) to prevent CSRF attacks. The value must exactly match the value of the csrfToken cookie. */
                "x-csrf-token": components["parameters"]["XCsrfToken"];
            };
            path?: never;
            cookie: {
                /** @description CSRF token stored in a Lax cookie (readable by frontend JavaScript, HttpOnly=false). Must match the x-csrf-token header. Rotated on refresh. */
                csrfToken: components["parameters"]["CsrfTokenCookie"];
                /** @description HttpOnly Secure (in production) SameSite=Lax cookie containing the opaque refresh token. Rotated on refresh. Path=/. */
                "__Host-refresh": components["parameters"]["RefreshTokenCookie"];
            };
        };
        requestBody?: never;
        responses: {
            /** @description Token refreshed successfully. Cookies rotated. */
            200: {
                headers: {
                    /** @description Rotates __Host-refresh (HttpOnly) and csrfToken cookies. See components headers. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    logoutUser: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF token obtained from the csrfToken cookie. Required only on endpoints relying on cookie auth (POST /auth/refresh and POST /auth/logout) to prevent CSRF attacks. The value must exactly match the value of the csrfToken cookie. */
                "x-csrf-token": components["parameters"]["XCsrfToken"];
            };
            path?: never;
            cookie: {
                /** @description CSRF token stored in a Lax cookie (readable by frontend JavaScript, HttpOnly=false). Must match the x-csrf-token header. Rotated on refresh. */
                csrfToken: components["parameters"]["CsrfTokenCookie"];
                /** @description HttpOnly Secure SameSite=Lax cookie containing the opaque refresh token to revoke. */
                "__Host-refresh"?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful. Cookies cleared. */
            200: {
                headers: {
                    /** @description Clears __Host-refresh and csrfToken cookies by setting Max-Age=0. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Opaque verification token. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Email verified successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    resendVerificationEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Registered email address of the account. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationRequest"];
            };
        };
        responses: {
            /** @description Verification email sent if account exists and is unverified. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Registered email address of the account. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Password reset link sent if account exists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Opaque reset token and new password credentials. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password reset successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
